language: c

sudo: required
dist: xenial

# don't build tags separately
if: tag IS blank

compiler:
  - gcc
  - clang

cache: ccache

before_install:
  - travis_retry ./scripts/test.sh deps
  - travis_retry ./scripts/test.sh pydeps

before_script:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 || true

script:
  - ./scripts/test.sh

after_success:
  if [ "$TEST" == "coverage" ]; then
    bash <(curl -s https://codecov.io/bash);
  fi

after_failure:
  - cat config.log

env:
  global:
    - TESTS_REDUCED_KEYLENGTHS=yes
    - LEAK_DETECTIVE=no
    - MONOLITHIC=no
  matrix:
    - TEST=vpp VPP_VERSION=18.10
    - TEST=vpp VPP_VERSION=master
